apiVersion: "serving.kserve.io/v1alpha1"
kind: ClusterStorageContainer
metadata:
  name: model-registry-storage-initializer
spec:
  container:
    name: storage-initializer
    image: ghcr.io/kubeflow/model-registry/storage-initializer:latest
    env:
    - name: MODEL_REGISTRY_BASE_URL
      value: "model-registry-service.kubeflow.svc.cluster.local:8080"
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 1Gi
        cpu: "1"
  supportedUriFormats:
    - prefix: model-registry://
