---
# yaml-language-server: $schema=https://kubernetes-schemas.solanyn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kfp
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kfp-secret
    template:
      data:
        KUBEFLOW_MARIADB_USER: "{{ .KUBEFLOW_MARIADB_USER }}"
        KUBEFLOW_MARIADB_PASSWORD: "{{ .KUBEFLOW_MARIADB_PASSWORD }}"
  dataFrom:
    - extract:
        key: kubeflow
