
---
# yaml-language-server: $schema=https://kubernetes-schemas.solanyn.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: katib
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: katib-secret
    template:
      data:
        KATIB_MYSQL_DB_DATABASE: katib
        KATIB_MYSQL_DB_HOST: mariadb.database.svc.cluster.local
        KATIB_MYSQL_DB_PORT: "3306"
        DB_USER: "{{ .KUBEFLOW_MARIADB_USER }}"
        DB_PASSWORD: "{{ .KUBEFLOW_MARIADB_PASSWORD }}"
  dataFrom:
    - extract:
        key: kubeflow
